сделал, тесты постмана проходит
PetrovEgorVladimirovich1/java-filmorate pull request #17
Opened 2023-12-02 19:58 UTC by DmitriyDemintsev

аннотацию @Past в кастомной аннотации для валидации даты релиза убрал, так как с ней валились тесты постмана.

2023-12-02 22:13 UTC, ism-ektb commented
Надо в новую таблицу films_director добавить аннотацию позволяющую удалять из нее данные связанные с другими таблицами каскадом
Например,
user_id BIGINT NOT NULL REFERENCES users (id) **ON DELETE CASCADE**,
Это нужно для прохождения следующих тестов 
А так то, работа хорошая надо "мержить"

2023-12-03 14:59 UTC, ism-ektb requested changes
Можно мержить, с учетом замечаний

2023-12-04 12:31 UTC, PetrovEgorVladimirovich1 approved these changes

2023-12-04 12:59 UTC, ism-ektb approved these changes

2023-12-04 17:22 UTC, merged