Первая попытка.
PetrovEgorVladimirovich1/java-filmorate pull request #3
Opened 2023-10-08 11:04 UTC by PetrovEgorVladimirovich1

2023-10-08 12:02 UTC, db-exp requested changes

2023-10-08 12:02 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validate(Film film) {
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-validation</artifactId>
</dependency> 

Можно добавить и эти проверки сделать через Valid
Кастомную валидацию для 1895 года тоже можно сделать  https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4

2023-10-10 15:13 UTC, PetrovEgorVladimirovich1 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validate(Film film) {
время потратил прилично, но выполнил)

2023-10-10 19:32 UTC, db-exp approved these changes

2023-10-10 19:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank
на следующий спринт - не нужно и NotBlank и NotNull одновременно) NotBlank проверяет и null
А если стоит NotBlank, то лучше и Size ставить

2023-10-11 05:46 UTC, PetrovEgorVladimirovich1 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank
спасибо, учту)
теперь же я могу нажать Merge pull request?)

2023-10-12 18:20 UTC, merged